id: P486812B9
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ296779
  title: རྒྱ་གཞུང་གནད་ཆེ་བདམ་བསྒྲིགས།
  volumes:
    6526c9e2f41042819cd7f878d41675db:
      image_group_id: I4CZ298999
      title: ''
      base_file: v001.txt
  author: ''
